=== joaquinmadrid25/actividad-validacion-xml-xsd/expresionesRegulares.xsd
<?xml version = "1.0" encoding = "UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="expresionesRegulares">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="usuario" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="apellido" type="xs:string"/>
                            
                            <xs:element name="email">
                               <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            
                            <xs:element name="telefono">
                              <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[6789][0-9]{8}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            
                            <xs:element name="codigoPostal">
                              <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="(0[1-9]|[1-4][0-9]|5[0-2])[0-9]{3}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            
                            <xs:element name="nombreUsuario">
                               <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[a-z][a-z0-9_]{3,15}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            
                            <xs:element name="contrasena">
                               <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[^A-Za-z0-9]).{8,}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                        </xs:sequence>
                        <xs:attribute name="id" type="xs:int" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
</xs:schema>

=== joaquinmadrid25/actividad-validacion-xml-xsd/expresionesRegulares.xml
<?xml version="1.0" encoding="UTF-8"?>
<expresionesRegulares>
<xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="expresionesRegulares.xsd">
    <usuario id="1">
        <nombre>Joaquin</nombre>
        <apellido>Madrid</apellido>
        <email>joaquinmadrid@gmail.com</email>
        <telefono>622070250</telefono>
        <codigoPostal>41940</codigoPostal>
        <nombreUsuario>Joaquin</nombreUsuario>
        <contrasena>Joaquin05!</contrasena>
    </usuario> 
    <usuario id="2">
        <nombre>Juan</nombre>
        <apellido>Garcia</apellido>
        <email>juangarcia@gmail.com</email>
        <telefono>234567895</telefono>
        <codigoPostal>50980</codigoPostal>
        <nombreUsuario>Juan</nombreUsuario>
        <contrasena>JuanG4#23</contrasena>
    </usuario>
    <usuario id="3">
        <nombre>Pedro</nombre>
        <apellido>Lopez</apellido>
        <email>pedrolopez@gmail.com</email>
        <telefono>146879895</telefono>
        <codigoPostal>60759</codigoPostal>
        <nombreUsuario>Pedro</nombreUsuario>
        <contrasena>PedroL9@21</contrasena>
    </usuario>
</expresionesRegulares>
